owner: LYNGMN
repo: status

sites:
  - name: update.youngmin.kr
    url: https://update.youngmin.kr/
  - name: go.youngmin.kr
    url: https://go.youngmin.kr/
    
status-website:
  cname: status.youngmin.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | YOUNGMIN
  introTitle: "**Status** for YOUNGMIN"
  introMessage: 영민 웹모니터
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Post
      href: https://go.youngmin.kr/update
    - title: Community
      href: https://go.youngmin.kr/community
